# Generated by Django 3.1.5 on 2021-01-23 09:55

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('percentage', models.CharField(default='0', max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('icon', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('parent_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialty', to='myapp.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('challenge', tinymce.models.HTMLField()),
                ('process', tinymce.models.HTMLField()),
                ('conclusion', tinymce.models.HTMLField()),
                ('cover_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('bg_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('website', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_role', to='myapp.skill')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
