# Generated by Django 3.1.5 on 2021-01-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_projecttechnology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='image',
        ),
    ]
