# Generated by Django 3.1.5 on 2021-03-05 11:37

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_skill_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='parent_skill',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skill',
        ),
        migrations.AddField(
            model_name='project',
            name='project_technologies',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='skill',
            name='specialties',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), null=True, size=None),
        ),
        migrations.DeleteModel(
            name='ProjectTechnology',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(to='myapp.Language'),
        ),
    ]
