# Generated by Django 3.1.5 on 2021-03-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210305_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='languages',
        ),
        migrations.AddField(
            model_name='language',
            name='projects',
            field=models.ManyToManyField(related_name='projects', to='myapp.Project'),
        ),
    ]
