# Generated by Django 3.1.5 on 2021-03-05 12:20

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210305_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), null=True, size=None),
        ),
    ]
